# -*- coding: utf-8 -*-
"""AI first  lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GV3h3W8o7H9YBvBplOGLdkXfUSRDmiNp
"""



"""# Addition

"""

a=5
b=4
c=a+b
print(c)

"""# Subtract"""

a=5
b=4
c=a-b
print(c)

"""# Divide"""

a=25
b=5
c=a/b
print(c)

"""# Multiplication"""

a=5
b=4
c=a*b
print(c)