# -*- coding: utf-8 -*-
"""Lab 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxnOpgr3jb42g-OU2M1U4bagFk-aaO0G

#**Task 1: Lists**
"""

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print('Original Lists: ', numbers)

print('Sum:',sum(numbers) ) # Sum of array
print('Max:',max(numbers) ) # Max of array
print('Min:',min(numbers) ) # Min of array

numbers.append(11) # Add 11 to the end of the array
numbers.remove(10) # Remove 11 from the array
print('Modified Lists: ', numbers)

print('Ascending Order:',sorted(numbers) ) # Sort array in ascending order
print('Descending Order:',sorted(numbers, reverse=True) ) # Sort array in descending order

"""#**Task 2: Tuples**"""

fruits = ("apple", "banana", "cherry", "date", "elderberry") #we can't add or remove items from a tuple
print(fruits)
print('second item: ', fruits[1])
print('last item: ', fruits[-1])

#fruits[0]='guava' # we can't change items in a tuple
#print(fruits)

#fruits_list = list(fruits)
#print(fruits_list)

"""# **Task 3: Sets**"""

set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

print('Union:',set1.union(set2) ) # Union of sets
print('Intersection:',set1.intersection(set2) ) # Intersection of sets
print('Difference:',set1.difference(set2) ) # Difference of sets
print('Symmetric Difference:',set1.symmetric_difference(set2) ) # Symmetric Difference of sets

"""#**Task 4: Dictionaries**"""

students = {
 'Alice': 123,
 'Bob': 456,
 'Charlie': 789
}
print(students)

print('Keys: ',students.keys() )
print('Values: ',students.values() )

students['Alice'] = 321
print(students)
print('Alice:',students['Alice'] )

"""#**Task 5: Numpy**

# **Task 6: Matplotlib**
"""